import { useState } from 'react'
import { Sparkles, AlertCircle, Loader2, FlaskConical, Cpu, MapPin, Users, Check, UserPlus, ChevronDown, Columns2, Lock } from 'lucide-react'
import { generateShotPlan } from '../lib/generateShotPlan.js'
import { getDemoShotPlan } from '../lib/demoShotPlan.js'
import { resolveAtSlugs } from '../lib/storage.js'

// Small badge shown on fields that are locked because Demo presets apply.
function PresetTag() {
  return (
    <span className="inline-flex items-center gap-1 text-[10px] font-semibold text-amber-400 bg-amber-500/15 border border-amber-500/40 px-1.5 py-0.5 rounded-full">
      <Lock size={9} /> preset
    </span>
  )
}

const STYLES = ['Cinematic', 'Whiteboard Animation', 'Documentary', 'Minimalist', 'Infographic', 'Studio Lecture']
const TONES = ['Professional', 'Conversational', 'Inspiring', 'Friendly', 'Authoritative']
const DURATIONS = ['1–2 minutes', '3–5 minutes', '5–10 minutes', '10–15 minutes']
const AUDIENCES = ['Undergraduate Students', 'Postgraduate Students', 'Professional Learners', 'High School Students', 'General Public']

const EXAMPLES = [
  {
    label: 'Neural Networks',
    topic: 'Introduction to Neural Networks',
    objectives: 'Explain what a neural network is, how neurons and layers work together, and how a network learns from data.',
    audience: 'Undergraduate Students',
    duration: '3–5 minutes',
    style: 'Cinematic',
    tone: 'Inspiring',
    demoVariant: 'neural',
    demoReady: true,
  },
  {
    label: 'Quantum',
    topic: 'Introduction to Quantum Entanglement',
    objectives: 'Understand what entanglement is, why it matters for quantum computing, and dispel common misconceptions. Set the scene @lecture_hall.',
    audience: 'Undergraduate Students',
    duration: '3–5 minutes',
    style: 'Cinematic',
    tone: 'Inspiring',
  },
  {
    label: 'Immune System',
    topic: 'How the Immune System Fights a Virus',
    objectives: 'Explain innate vs adaptive immunity, the macrophage alarm, and antibody production in a visual, memorable way',
    audience: 'High School Students',
    duration: '3–5 minutes',
    style: 'Infographic',
    tone: 'Friendly',
    splitScreen: false,
    demoVariant: 'immune',
    demoReady: true,
  },
  {
    label: '★ LessonForge (self-demo)',
    topic: 'LessonForge, Explained by LessonForge',
    objectives: 'A self-referential product walkthrough: the instructor explains how LessonForge turns one lesson brief into a personalised, consistent video — generated by the very system doing the explaining. Walk through the brief, the AI planning agents, human-in-the-loop review, and cloud rendering. Doubles as the hackathon submission video.',
    audience: 'Professional Learners',
    duration: '3–5 minutes',
    style: 'Studio Lecture',
    tone: 'Inspiring',
    splitScreen: true,
    demoVariant: 'lessonforge',
    educatorName: 'Dr. Sarah Chen',
    demoReady: true,
  },
  {
    label: 'Hastings 1066',
    topic: 'The Battle of Hastings, 1066',
    objectives: 'Recount the clash between King Harold II and William of Normandy: the shield wall on Senlac Hill, the feigned Norman retreats, the death of Harold, and why 1066 reshaped England forever. Open with the educator introducing the stakes, then cut to cinematic battlefield scenes of the Saxon shield wall, charging Norman cavalry, and archers, before returning to the educator to draw out the lasting consequences.',
    audience: 'High School Students',
    duration: '3–5 minutes',
    style: 'Cinematic',
    tone: 'Authoritative',
  },
]

export default function LessonForm({ settings, onShotPlanGenerated, demoMode, educators = [], selectedEducatorIds = [], setSelectedEducatorIds = () => {}, locations = [], compact = false, shotPlan = null }) {
  const [form, setForm] = useState({
    topic: '',
    objectives: '',
    audience: AUDIENCES[0],
    duration: DURATIONS[1],
    style: STYLES[0],
    tone: TONES[0],
    splitScreen: false,
    presenterBackdrop: null, // location slug used as the presenter's backdrop
    demoVariant: 'neural',
  })
  // Pickers collapse to save vertical space; open by default only when empty.
  const [eduOpen, setEduOpen] = useState(selectedEducatorIds.length === 0)
  const [locOpen, setLocOpen] = useState(false)
  const [topicOpen, setTopicOpen] = useState(true)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)

  const set = (k, v) => setForm(f => ({ ...f, [k]: v }))

  // Educators chosen for this lesson (drives both prompt text and faceswap).
  const chosenEducators = educators.filter(e => selectedEducatorIds.includes(e.id))
  // Single presenter per lesson: selecting an educator replaces any previous
  // choice (click again to deselect). Only one presenter is ever rendered, so
  // the picker is now single-select to match reality.
  const toggleEducator = (id) =>
    setSelectedEducatorIds(prev => prev.includes(id) ? [] : [id])

  // Single-select: only one location @slug may be active at a time.
  const isLocationActive = (slug) => new RegExp(`@${slug}(?![\\w-])`).test(form.objectives)
  const toggleLocation = (slug) => {
    setForm(f => {
      const active = new RegExp(`@${slug}(?![\\w-])`).test(f.objectives)
      // Strip ALL known location slugs first (enforces single-select).
      let objectives = f.objectives
      for (const loc of locations) {
        objectives = objectives.replace(new RegExp(`\\s*@${loc.slug}(?![\\w-])`, 'g'), '')
      }
      objectives = objectives.replace(/\s{2,}/g, ' ').trim()
      // Clicking the already-active location just clears it; otherwise set the new one.
      if (active) return { ...f, objectives }
      const sep = objectives.length > 0 ? ' ' : ''
      return { ...f, objectives: `${objectives}${sep}@${slug}` }
    })
  }

  // Detect @slug references in the objectives field
  const atSlugs = (form.objectives.match(/@([\w_-]+)/g) || [])
  const matchedSlugs = atSlugs.filter(s => locations.find(l => `@${l.slug}` === s))
  const unknownSlugs = atSlugs.filter(s => !locations.find(l => `@${l.slug}` === s))
  const activeLocations = locations.filter(l => atSlugs.includes(`@${l.slug}`))

  const handleGenerate = async () => {
    // Locked / bespoke lessons (e.g. the hand-authored self-demo) must never be
    // sent through the LLM or rebuilt from a variant. "Regenerate" just re-emits
    // the exact stored plan — render-time fixes (wardrobe pinning, voiceover
    // timing) still apply downstream. This preserves the hand-tuned shots.
    if (shotPlan?.locked) {
      onShotPlanGenerated({ ...shotPlan })
      return
    }

    if (demoMode) {
      setLoading(true)
      setError(null)
      await new Promise(r => setTimeout(r, 1200))
      const backdrop = form.presenterBackdrop
        ? locations.find(l => l.slug === form.presenterBackdrop)
        : null
      onShotPlanGenerated(getDemoShotPlan({
        splitScreen: form.splitScreen,
        variant: form.demoVariant,
        backdrop,
        educator: chosenEducators[0] || educators[0] || null,
      }))
      setLoading(false)
      return
    }

    if (!form.topic.trim()) { setError('Please enter a lesson topic'); return }
    if (!form.objectives.trim()) { setError('Please enter learning objectives'); return }
    if (!settings.comfyEndpoint?.trim()) {
      setError('Please add your Alibaba Cloud backend URL in Settings — the Qwen agents run through it. Or enable Demo Mode to try without a backend.')
      return
    }
    setError(null)
    setLoading(true)
    try {
      // Resolve @slug references before sending to LLM
      const { resolved: resolvedObjectives } = resolveAtSlugs(form.objectives, locations)
      const plan = await generateShotPlan({
        ...form,
        resolvedObjectives,
        educators: chosenEducators.length > 0 ? chosenEducators : (educators.length > 0 ? educators : undefined),
      }, settings)
      onShotPlanGenerated(plan)
    } catch (err) {
      setError(err.message)
    } finally {
      setLoading(false)
    }
  }

  const loadExample = (ex) => {
    setForm({ ...form, demoVariant: 'neural', ...ex })
    // Auto-select the educator this template is written for, so the on-screen
    // presenter, the generated base image's gender, and the voice all match —
    // and so the educator visibly shows as selected in the modal.
    // Only default the presenter if the user hasn't already chosen one — picking
    // a template must NOT reset a presenter you deliberately selected.
    if (ex.educatorName && educators.length && selectedEducatorIds.length === 0) {
      const match = educators.find(
        e => (e.name || '').toLowerCase() === ex.educatorName.toLowerCase()
      )
      if (match) setSelectedEducatorIds([match.id])
    }
  }

  return (
    <div className="space-y-6">

      {/* Hero — hidden in compact/modal mode */}
      {!compact && (<>
      <div className="relative overflow-hidden rounded-2xl border border-gray-800 bg-gradient-to-br from-gray-900 via-gray-900 to-brand-950 p-8 text-center">
        <div className="absolute inset-0 bg-gradient-to-br from-brand-600/5 via-transparent to-red-600/5 pointer-events-none" />
        <div className="absolute -top-16 -right-16 w-64 h-64 bg-brand-600/10 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute -bottom-16 -left-16 w-64 h-64 bg-red-600/10 rounded-full blur-3xl pointer-events-none" />

        <div className="relative">
          <div className="inline-flex items-center gap-2 bg-red-950/60 border border-red-800/60 rounded-full px-4 py-1.5 mb-4">
            <Cpu size={13} className="text-red-400" />
            <span className="text-xs font-semibold text-orange-400 uppercase tracking-wider">Alibaba Cloud · AI Showrunner</span>
          </div>

          <h1 className="text-4xl font-extrabold text-white mb-3 tracking-tight">
            Turn a lesson into a<br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-400 to-red-400">
              cinematic video
            </span>
          </h1>

          <p className="text-gray-400 max-w-xl mx-auto text-base leading-relaxed">
            Describe your lesson. LessonForge generates a complete shot-by-shot production plan —
            voiceover scripts, cinematic prompts, and direct integration with your own
            <span className="text-orange-400 font-medium"> Wan on Alibaba Cloud</span> video render backend.
          </p>

          <div className="flex flex-wrap gap-2 justify-center mt-5">
            {['Qwen agents', 'Wan 2.7 video', 'Reusable Educators', '@Location slugs', 'YAML Export'].map(f => (
              <span key={f} className="text-xs bg-gray-800/80 border border-gray-700 text-gray-300 px-3 py-1 rounded-full">{f}</span>
            ))}
          </div>

          {demoMode && (
            <div className="mt-5 inline-flex items-center gap-2 bg-amber-500/10 border border-amber-500/30 rounded-xl px-5 py-3">
              <FlaskConical size={15} className="text-amber-400" />
              <span className="text-sm text-amber-300 font-medium">
                Demo mode — click Generate to see a full sample shot plan instantly, no API key needed
              </span>
            </div>
          )}

          <div className="flex gap-2 justify-center mt-4">
            {EXAMPLES.map((ex, i) => (
              <button key={i} onClick={() => loadExample(ex)}
                className="text-xs font-medium bg-amber-500/15 hover:bg-amber-500/25 text-amber-300 hover:text-amber-200 px-3 py-1.5 rounded-full transition-colors border border-amber-500/40 hover:border-amber-400 flex items-center gap-1.5">
                <Sparkles size={11} className="text-amber-400 shrink-0" />
                Try: {ex.topic.split(' ').slice(0, 3).join(' ')}…
              </button>
            ))}
          </div>
        </div>
      </div>

      </>)}

      {/* ── Educator picker ──────────────────────────────────────────────── */}
      <div className="card space-y-3">
        <button type="button" onClick={() => setEduOpen(o => !o)}
          className="w-full flex items-center justify-between gap-2 text-left">
          <label className="label mb-0 flex items-center gap-2 cursor-pointer pointer-events-none">
            <Users size={14} className="text-brand-400" />
            Presenter
            <span className="text-xs text-gray-600 font-normal hidden sm:inline">— whose face & voice anchors the lesson</span>
          </label>
          <span className="flex items-center gap-2 shrink-0">
            {chosenEducators.length > 0 && (
              <span className="text-xs text-brand-400 font-medium truncate max-w-[160px]">
                {chosenEducators[0]?.name}
              </span>
            )}
            <ChevronDown size={16} className={`text-gray-500 transition-transform ${eduOpen ? 'rotate-180' : ''}`} />
          </span>
        </button>

        {eduOpen && (educators.length === 0 ? (
          <div className="flex items-center gap-3 rounded-lg border border-dashed border-gray-700 px-4 py-3">
            <UserPlus size={16} className="text-gray-500 shrink-0" />
            <p className="text-sm text-gray-500">
              No educators yet — add one in the <span className="text-brand-400 font-medium">Educators</span> tab to give your lesson a consistent on-screen presenter.
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
            {educators.map(ed => {
              const selected = selectedEducatorIds.includes(ed.id)
              const initials = ed.name.split(' ').map(n => n[0]).join('').slice(0, 2)
              // In Demo Mode only Dr. Sarah Chen is selectable; the rest are locked.
              const demoLocked = demoMode && (ed.name || '').toLowerCase() !== 'dr. sarah chen'
              return (
                <button key={ed.id} type="button" disabled={demoLocked}
                  onClick={() => { if (!demoLocked) toggleEducator(ed.id) }}
                  title={demoLocked ? 'Locked \u2014 Demo uses Dr. Sarah Chen' : undefined}
                  className={`relative flex items-center gap-3 rounded-xl border p-2.5 text-left transition-all ${
                    demoLocked
                      ? 'border-gray-800/60 bg-gray-900/30 opacity-40 cursor-not-allowed'
                      : selected
                      ? 'border-brand-600 bg-brand-950/40 ring-1 ring-brand-600/40'
                      : 'border-gray-800 bg-gray-900/60 hover:border-gray-700'
                  }`}>
                  {ed.portrait ? (
                    <img src={ed.portrait} alt={ed.name}
                      className="w-10 h-10 rounded-lg object-cover border border-gray-700 shrink-0" />
                  ) : (
                    <div className="w-10 h-10 rounded-lg bg-brand-800 flex items-center justify-center text-xs font-bold text-white shrink-0">
                      {initials}
                    </div>
                  )}
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-semibold text-white truncate">{ed.name}</p>
                    <p className="text-[11px] text-gray-500 truncate">{ed.role || 'Educator'}</p>
                  </div>
                  {selected && (
                    <span className="absolute top-1.5 right-1.5 w-4 h-4 rounded-full bg-brand-500 flex items-center justify-center">
                      <Check size={11} className="text-white" />
                    </span>
                  )}
                  {demoLocked && (
                    <span className="absolute top-1.5 right-1.5 w-4 h-4 rounded-full bg-gray-700 flex items-center justify-center">
                      <Lock size={9} className="text-gray-300" />
                    </span>
                  )}
                  {!ed.portrait && !demoLocked && (
                    <span className="absolute bottom-1.5 right-1.5 text-[9px] text-amber-400" title="No portrait — needed for educator likeness">no photo</span>
                  )}
                </button>
              )
            })}
          </div>
        ))}

        {eduOpen && form.demoVariant === 'lessonforge' && (
          <p className="text-xs text-brand-300 flex items-center gap-1.5">
            <Check size={12} /> Pick any educator above — they become the narrator. Their face, gender and voice all follow your choice (this template just defaults to Dr. Sarah Chen).
          </p>
        )}

        {eduOpen && chosenEducators.length > 0 && !chosenEducators[0].portrait && (
          <p className="text-xs text-amber-400 flex items-center gap-1.5">
            <AlertCircle size={12} /> Selected educator has no portrait — add one in the Educators tab for educator-consistent rendering.
          </p>
        )}
      </div>

      {/* ── Location picker ──────────────────────────────────── */}
      <div className="card space-y-3">
        <button type="button" onClick={() => setLocOpen(o => !o)}
          className="w-full flex items-center justify-between gap-2 text-left">
          <label className="label mb-0 flex items-center gap-2 cursor-pointer pointer-events-none">
            <MapPin size={14} className="text-brand-400" />
            Location
            <span className="text-xs text-gray-600 font-normal hidden sm:inline">— where the lesson is set</span>
          </label>
          <span className="flex items-center gap-2 shrink-0">
            {activeLocations.length > 0 && (
              <span className="text-xs text-brand-400 font-medium truncate max-w-[140px]">{activeLocations[0].name || activeLocations[0].slug}</span>
            )}
            <ChevronDown size={16} className={`text-gray-500 transition-transform ${locOpen ? 'rotate-180' : ''}`} />
          </span>
        </button>

        {locOpen && (locations.length === 0 ? (
          <div className="flex items-center gap-3 rounded-lg border border-dashed border-gray-700 px-4 py-3">
            <MapPin size={16} className="text-gray-500 shrink-0" />
            <p className="text-sm text-gray-500">
              No locations yet — add one in the <span className="text-brand-400 font-medium">Locations</span> tab to set a consistent scene, or just describe it in the objectives.
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {locations.map(loc => {
              const selected = isLocationActive(loc.slug)
              return (
                <button key={loc.slug} type="button" onClick={() => toggleLocation(loc.slug)}
                  disabled={demoMode}
                  className={`relative flex items-start gap-3 rounded-xl border p-3 text-left transition-all disabled:opacity-50 disabled:cursor-not-allowed ${
                    selected
                      ? 'border-brand-600 bg-brand-950/40 ring-1 ring-brand-600/40'
                      : 'border-gray-800 bg-gray-900/60 hover:border-gray-700'
                  }`}>
                  <div className={`w-9 h-9 rounded-lg flex items-center justify-center shrink-0 ${selected ? 'bg-brand-700' : 'bg-gray-800'}`}>
                    <MapPin size={15} className={selected ? 'text-white' : 'text-gray-400'} />
                  </div>
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2">
                      <p className="text-sm font-semibold text-white truncate">{loc.name}</p>
                      <code className="text-[10px] bg-gray-800 text-red-300 px-1.5 py-0.5 rounded shrink-0">@{loc.slug}</code>
                    </div>
                    <p className="text-[11px] text-gray-500 line-clamp-2 mt-0.5">{loc.description}</p>
                  </div>
                  {selected && (
                    <span className="absolute top-1.5 right-1.5 w-4 h-4 rounded-full bg-brand-500 flex items-center justify-center">
                      <Check size={11} className="text-white" />
                    </span>
                  )}
                </button>
              )
            })}
          </div>
        ))}

        {locOpen && demoMode && locations.length > 0 && (
          <p className="text-xs text-gray-600 flex items-center gap-1.5">
            <FlaskConical size={11} className="text-amber-400" /> Location selection is disabled in demo mode.
          </p>
        )}
      </div>

      {/* Form card */}
      <div className="card space-y-5">
        <button type="button" onClick={() => setTopicOpen(o => !o)}
          className="w-full flex items-center justify-between gap-2 text-left">
          <label className="label mb-0 flex items-center gap-2 cursor-pointer pointer-events-none">
            <Sparkles size={14} className="text-brand-400" />
            Lesson Details
            <span className="text-xs text-gray-600 font-normal hidden sm:inline">— topic, objectives & style</span>
          </label>
          <span className="flex items-center gap-2 shrink-0">
            {form.topic?.trim() && (
              <span className="text-xs text-brand-400 font-medium truncate max-w-[180px]">{form.topic}</span>
            )}
            <ChevronDown size={16} className={`text-gray-500 transition-transform ${topicOpen ? 'rotate-180' : ''}`} />
          </span>
        </button>

        {topicOpen && (<>
        <div>
          <label className="label flex items-center gap-2">Lesson Topic <span className="text-red-400">*</span>{demoMode && <PresetTag />}</label>
          <input className="input" value={form.topic} onChange={e => set('topic', e.target.value)}
            placeholder={demoMode ? 'e.g. Introduction to Neural Networks (or just hit Generate!)' : 'e.g. Introduction to Machine Learning'}
            disabled={demoMode} />

          {/* Sample lessons — single scrollable row of bold orange chips.
              In demo mode the topic field is disabled, but templates still set
              the demo variant + split layout, so keep them available. */}
          <div className="flex items-center gap-2 mt-2.5 overflow-x-auto no-scrollbar -mx-1 px-1 pb-0.5">
            <span className="text-xs text-amber-500 font-semibold flex items-center gap-1 shrink-0">
              <Sparkles size={12} /> {demoMode ? 'Demo templates:' : 'Samples:'}
            </span>
            {(demoMode ? EXAMPLES.filter(e => e.demoVariant === 'immune') : EXAMPLES).map((ex, i) => {
              const active = demoMode && form.demoVariant === (ex.demoVariant || 'neural')
              return (
                <button key={i} type="button" onClick={() => loadExample(ex)}
                  className={`shrink-0 text-xs font-semibold px-3 py-1.5 rounded-full transition-colors flex items-center gap-1.5 shadow-sm ${
                    active
                      ? 'bg-brand-500 hover:bg-brand-400 text-white shadow-brand-500/30 ring-2 ring-brand-400/50'
                      : 'bg-amber-500 hover:bg-amber-400 text-gray-900 shadow-amber-500/20'
                  }`}>
                  <Sparkles size={11} className="shrink-0" />
                  {ex.label || ex.topic}
                </button>
              )
            })}
          </div>
        </div>

        <div>
          <label className="label flex items-center gap-2">
            Learning Objectives <span className="text-red-400">*</span>{demoMode && <PresetTag />}
            {locations.length > 0 && (
              <span className="text-xs text-gray-600 font-normal flex items-center gap-1">
                <MapPin size={11} /> use <code className="bg-gray-800 px-1 rounded text-red-300">@slug</code> to set a location
              </span>
            )}
          </label>
          <textarea className="input resize-none" rows={3} value={form.objectives}
            onChange={e => set('objectives', e.target.value)}
            placeholder={demoMode
              ? 'Not needed in demo mode — just hit Generate below'
              : locations.length > 0
                ? 'What should students understand after watching? Use @gpu_lab or @lecture_hall to set the scene...'
                : 'What should students understand or be able to do after watching?'}
            disabled={demoMode} />

          {/* @slug feedback */}
          {matchedSlugs.length > 0 && (
            <div className="flex flex-wrap gap-1.5 mt-2">
              {matchedSlugs.map(s => (
                <span key={s} className="inline-flex items-center gap-1 text-xs bg-red-950/40 border border-red-900/50 text-red-300 px-2 py-0.5 rounded-full">
                  <MapPin size={10} /> {s} resolved
                </span>
              ))}
            </div>
          )}
          {unknownSlugs.length > 0 && (
            <div className="flex flex-wrap gap-1.5 mt-2">
              {unknownSlugs.map(s => (
                <span key={s} className="inline-flex items-center gap-1 text-xs bg-yellow-950/40 border border-yellow-900/50 text-yellow-400 px-2 py-0.5 rounded-full">
                  ⚠ {s} — not found
                </span>
              ))}
            </div>
          )}

          {/* Available slugs hint */}
          {locations.length > 0 && !demoMode && (
            <div className="flex flex-wrap gap-1.5 mt-2">
              <span className="text-xs text-gray-600">Available:</span>
              {locations.map(l => (
                <button key={l.slug} type="button"
                  onClick={() => set('objectives', form.objectives + ` @${l.slug}`)}
                  className="text-xs bg-gray-800 hover:bg-gray-700 text-gray-400 hover:text-red-300 px-2 py-0.5 rounded-full border border-gray-700 transition-colors">
                  @{l.slug}
                </button>
              ))}
            </div>
          )}
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
          {[
            { label: 'Audience', key: 'audience', options: AUDIENCES },
            { label: 'Duration', key: 'duration', options: DURATIONS },
            { label: 'Visual Style', key: 'style', options: STYLES },
            { label: 'Tone', key: 'tone', options: TONES },
          ].map(({ label, key, options }) => (
            <div key={key}>
              <label className="label flex items-center gap-2">{label}{demoMode && <PresetTag />}</label>
              <select className="input" value={form[key]} onChange={e => set(key, e.target.value)} disabled={demoMode}>
                {options.map(o => <option key={o}>{o}</option>)}
              </select>
            </div>
          ))}
        </div>

        {/* ── Split-screen presenter layout ──────────────────────────────── */}
        <button type="button"
          disabled={demoMode && form.demoVariant === 'lessonforge'}
          onClick={() => set('splitScreen', !form.splitScreen)}
          className={`w-full flex items-center gap-3 rounded-xl border px-4 py-3 text-left transition-colors ${
            form.splitScreen
              ? 'border-brand-500/60 bg-brand-500/10'
              : 'border-gray-800 bg-gray-900/40 hover:border-gray-700'
          } ${demoMode && form.demoVariant === 'lessonforge' ? 'opacity-70 cursor-not-allowed' : ''}`}>
          <div className={`shrink-0 grid place-items-center h-9 w-9 rounded-lg ${form.splitScreen ? 'bg-brand-500/20 text-brand-300' : 'bg-gray-800 text-gray-500'}`}>
            <Columns2 size={17} />
          </div>
          <div className="flex-1 min-w-0">
            <p className="text-sm font-semibold text-white flex items-center gap-2">
              Split-screen presenter
              <span className="text-[10px] uppercase tracking-wide text-brand-300 bg-brand-500/15 border border-brand-500/30 rounded px-1.5 py-0.5">Layout</span>
            </p>
            <p className="text-xs text-gray-500 mt-0.5">
              Presenter talking-head on the left (30%), lesson visuals without the presenter on the right (70%).
              {demoMode && form.demoVariant === 'lessonforge' && <span className="text-brand-300"> Locked on for the demo.</span>}
            </p>
          </div>
          {/* switch */}
          <span className={`shrink-0 relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${form.splitScreen ? 'bg-brand-500' : 'bg-gray-700'}`}>
            <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${form.splitScreen ? 'translate-x-6' : 'translate-x-1'}`} />
          </span>
        </button>

        {/* Presenter backdrop — only when split-screen is on. Places the
            presenter *in* a chosen location instead of a floating portrait. */}
        {form.splitScreen && (
          <div className="rounded-xl border border-gray-800 bg-gray-900/40 px-4 py-3">
            <div className="flex items-center gap-2 mb-2">
              <MapPin size={14} className="text-brand-300" />
              <p className="text-sm font-semibold text-white">Presenter backdrop</p>
              <span className="text-xs text-gray-500">— where the presenter is filmed</span>
            </div>
            {locations.length === 0 ? (
              <p className="text-xs text-gray-600">Add a Location to use it as a backdrop. Defaults to a neutral studio.</p>
            ) : (
              <div className="flex flex-wrap gap-2">
                <button type="button" onClick={() => set('presenterBackdrop', null)}
                  className={`text-xs font-medium px-3 py-1.5 rounded-full border transition-colors ${
                    !form.presenterBackdrop
                      ? 'bg-brand-500 text-white border-brand-400'
                      : 'bg-gray-800 text-gray-400 border-gray-700 hover:text-white'
                  }`}>
                  Neutral studio
                </button>
                {locations.map(l => (
                  <button key={l.slug} type="button" onClick={() => set('presenterBackdrop', l.slug)}
                    className={`flex items-center gap-2 text-xs font-medium pl-1.5 pr-3 py-1 rounded-full border transition-colors ${
                      form.presenterBackdrop === l.slug
                        ? 'bg-brand-500 text-white border-brand-400'
                        : 'bg-gray-800 text-gray-400 border-gray-700 hover:text-white'
                    }`}>
                    {l.image
                      ? <img src={l.image} alt="" className="h-5 w-5 rounded-full object-cover" />
                      : <span className="h-5 w-5 rounded-full bg-gray-700 grid place-items-center"><MapPin size={10} /></span>}
                    {l.name || l.slug}
                  </button>
                ))}
              </div>
            )}
          </div>
        )}
        </>)}

        {error && (
          <div className="flex items-start gap-2 bg-red-950/50 border border-red-900 rounded-lg px-4 py-3 text-red-400 text-sm">
            <AlertCircle size={16} className="mt-0.5 shrink-0" />
            <span>{error}</span>
          </div>
        )}

        <button onClick={handleGenerate} disabled={loading}
          className="btn-primary w-full flex items-center justify-center gap-2 text-base py-3">
          {loading ? (
            <><Loader2 size={18} className="animate-spin" /> {demoMode ? 'Loading demo shot plan…' : 'Generating Shot Plan…'}</>
          ) : shotPlan?.locked ? (
            <><Lock size={18} /> Reload Protected Shot Plan</>
          ) : demoMode ? (
            <><FlaskConical size={18} /> Generate Demo Shot Plan</>
          ) : (
            <><Sparkles size={18} /> Generate Shot Plan</>
          )}
        </button>

        {!demoMode && (
          <p className="text-xs text-center text-gray-600">
            No API key? Toggle <span className="text-amber-400 font-medium">Demo Mode</span> in the header to try the full UI instantly.
          </p>
        )}
      </div>
    </div>
  )
}
